select* from customer_shopping_behavior;
alter table customer_shopping_behavior
rename column `ï»¿Customer ID` to customer_id;

alter table customer_shopping_behavior
rename column `Discount Applied` to discount_applied;

alter table customer_shopping_behavior
rename column `Review Rating` to review_rating;

alter table customer_shopping_behavior
rename column `Shipping Type` to shipping_type;

alter table customer_shopping_behavior
rename column `Subscription Status` to subscription_status;

alter table customer_shopping_behavior
rename column `Previous Purchases` to previous_purchased;





#Q1 What is the total revenue generated by male vs female customer?
select gender, sum(purchase_amt) as revenue
from customer_shopping_behavior
group by gender;
select avg(purchase_amt) from customer_shopping_behavior;

#Q2 Which customers used a discount but still spent more than the avverage purchase amount?
select customer_id, purchase_amt
from customer_shopping_behavior
where discount_applied ="yes" and purchase_amt>=(select avg(purchase_amt) from customer_shopping_behavior);

#Q3 Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) as average_rating
from customer_shopping_behavior
group by Item_Purchased
order by avg(review_rating) desc
limit 5;

#Q4 Compare the average purchase amount between  Standard and Express Shipping.
select shipping_type, round(avg(purchase_amt),2)
from customer_shopping_behavior
where shipping_type in ('Express','Standard')
group by shipping_type;

#Q5 Do subscribed customers spend more? Compare average spend and totaal revenue between subscribers and non-subscribers.
select subscription_status, count(customer_id) as no_of_customers,round(avg(purchase_amt),2) as avg_spend,sum(purchase_amt) as revenue
from customer_shopping_behavior
group by subscription_status;

#Q6 which 5 product have the highest precentage of purchases with discount applied?
select item_purchased, 
round(100*sum(case when discount_applied="yes" then 1 else 0 
end)/count(*),2) as discount_rate
from customer_shopping_behavior
group by Item_Purchased
order by discount_rate desc
limit 5;

#Q7 Segment customers into New, Returning, and Loyal based on there total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id,previous_purchased, (case when previous_purchased=1 then 'New Customer'
                         when previous_purchased between 2 and 10 then 'Returning Customer'
                         else 'Loyal Customer'
                         end) as customer_segment
from customer_shopping_behavior)
select customer_segment,count(*)as no_of_customer
from customer_type
group by customer_segment;

#Q8 What are the top 3 most purchased products within each category?
with csb as (
select category,item_purchased,count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc)as item_rank
from customer_shopping_behavior
group by category,item_purchased)
select item_rank,category,item_purchased, total_orders
from csb
where item_rank <=3;

#Q9 Are customers who have repeat buyers(more than 5 previous purchases) also likey to subscribe?
 select subscription_status,count(customer_id) as repeat_buyer
 from customer_shopping_behavior
 where previous_purchased >5
 group by subscription_status;
 
 #Q10 What is total revenue contribution of each age group?
 with csb as(
select age,sum(purchase_amt) as sum_revenue , case when age between 13 and 19 then "teenager"
                 when age between 20 and 39 then "young adult"
                 when age between 40 and 59 then "middle-aged adult"
                 else "senior citizen"
                 end as age_group
                 from customer_shopping_behavior
                 group by age)
                 
select age_group,sum(sum_revenue) as total_revenue
from csb
group by age_group
order by total_revenue desc;
 

